// Code generated by hertz generator.

package main

import (
	handler "github.com/BiliGO/biz/handler"
	apihandler "github.com/BiliGO/biz/handler/api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizedRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 双 Token 刷新接口（无需 JWT 鉴权）
	r.POST("/user/refresh", apihandler.RefreshToken)
}
