// Code generated by hertz generator.

package auth

import (
	"context"

	"github.com/BiliGO/biz/mw"
	"github.com/BiliGO/biz/pkg/response"
	"github.com/BiliGO/biz/service"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetMFAQrcode .
// @router /auth/mfa/qrcode [GET]
func GetMFAQrcode(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)
	if userID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeUnauthorized, "unauthorized"))
		return
	}

	user, err := service.GetUserByID(ctx, userID)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeNotFound, "user not found"))
		return
	}

	result, err := service.GenerateMFAQrcode(ctx, userID, user.Username)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}

	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{
		"secret": result.Secret,
		"qrcode": result.Qrcode,
	}))
}
