// Code generated by hertz generator.

package api

import (
	"context"
	"fmt"
	"log"
	"os"
	"strconv"

	"github.com/BiliGO/biz/dal/minio"
	api "github.com/BiliGO/biz/model/api"
	"github.com/BiliGO/biz/mw"
	"github.com/BiliGO/biz/pkg/response"
	"github.com/BiliGO/biz/service"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req api.RegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}

	result, err := service.Register(ctx, req.Username, req.Password)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}

	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{
		"user_id":       result.UserID,
		"access_token":  result.AccessToken,
		"refresh_token": result.RefreshToken,
	}))
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req api.LoginReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}

	result, err := service.Login(ctx, req.Username, req.Password)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeUnauthorized, err.Error()))
		return
	}

	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{
		"user_id":       result.UserID,
		"access_token":  result.AccessToken,
		"refresh_token": result.RefreshToken,
	}))

}

// GetUserInfo .
// @router /user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var req api.UserInfoReq
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}

	var targetID int64
	if req.UserID != 0 {
		targetID = req.UserID
	} else {
		uid, _ := c.Get(mw.CtxUserIDKey)
		targetID, _ = uid.(int64)
	}
	if targetID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "user_id required"))
		return
	}

	info, err := service.GetUserInfo(ctx, targetID)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeNotFound, err.Error()))
		return
	}

	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{
		"user": map[string]interface{}{
			"id":              info.ID,
			"username":        info.Username,
			"avatar_url":      info.AvatarURL,
			"follower_count":  info.FollowerCount,
			"following_count": info.FollowingCount,
			"created_at":      info.CreatedAt,
			"updated_at":      info.UpdatedAt,
		},
	}))
}

// UploadAvatar .
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)
	if userID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeUnauthorized, "unauthorized"))
		return
	}

	file, err := c.FormFile("avatar")
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "avatar file required"))
		return
	}

	avatarURL, err := minio.UploadMultipartFile(ctx, "avatars", file)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, "failed to upload avatar to storage"))
		return
	}

	if err := service.UpdateAvatar(ctx, userID, avatarURL); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}

	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{
		"avatar_url": avatarURL,
	}))
}

// RefreshToken .
// @router /user/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	refreshToken := string(c.GetHeader("X-Refresh-Token"))
	if refreshToken == "" {
		c.JSON(consts.StatusOK, response.Fail(response.CodeUnauthorized, "refresh token required"))
		return
	}

	secret := os.Getenv("JWT_SECRET")
	claims, err := service.ParseRefreshToken(refreshToken, secret)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeUnauthorized, err.Error()))
		return
	}

	accessToken, newRefresh, err := service.RefreshTokens(ctx, claims.UserID)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}

	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{
		"user_id":       strconv.FormatInt(claims.UserID, 10),
		"access_token":  accessToken,
		"refresh_token": newRefresh,
	}))
}

// PublishVideo .
// @router /video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	log.Println("开始处理视频发布请求")
	defer log.Println("视频发布请求处理完成")

	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)
	log.Printf("用户ID: %d", userID)

	title := string(c.PostForm("title"))
	description := string(c.PostForm("description"))
	log.Printf("视频标题: %s, 描述: %s", title, description)

	const (
		maxVideoSize = 500 * 1024 * 1024
		maxCoverSize = 10 * 1024 * 1024
	)

	log.Println("开始获取视频文件")
	videoFile, err := c.FormFile("video")
	if err != nil {
		log.Printf("获取视频文件失败: %v", err)
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "video file required"))
		return
	}
	log.Printf("视频文件: %s, 大小: %d", videoFile.Filename, videoFile.Size)

	if videoFile.Size > maxVideoSize {
		log.Printf("视频文件过大: %d > %d", videoFile.Size, maxVideoSize)
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, fmt.Sprintf("video file too large, max size is %dMB", maxVideoSize/(1024*1024))))
		return
	}

	videoURL, err := minio.UploadMultipartFile(ctx, "videos", videoFile)
	if err != nil {
		log.Printf("上传视频到 MinIO 失败: %v", err)
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, "failed to upload video to storage"))
		return
	}
	log.Printf("视频URL: %s", videoURL)

	var coverURL string
	coverFile, err := c.FormFile("cover")
	if err == nil {
		log.Printf("封面文件: %s, 大小: %d", coverFile.Filename, coverFile.Size)
		if coverFile.Size > maxCoverSize {
			log.Printf("封面文件过大: %d > %d", coverFile.Size, maxCoverSize)
			c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, fmt.Sprintf("cover file too large, max size is %dMB", maxCoverSize/(1024*1024))))
			return
		}

		coverURL, err = minio.UploadMultipartFile(ctx, "covers", coverFile)
		if err != nil {
			log.Printf("上传封面到 MinIO 失败: %v", err)
			c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, "failed to upload cover to storage"))
			return
		}
		log.Printf("封面URL: %s", coverURL)
	} else {
		log.Println("未提供封面文件")
	}

	log.Println("开始调用服务层发布视频")
	item, err := service.PublishVideo(ctx, userID, title, description, videoURL, coverURL)
	if err != nil {
		log.Printf("发布视频失败: %v", err)
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	log.Println("视频发布成功")
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"video": item}))
}

// GetVideoList .
// @router /video/list [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Query("user_id")
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	var targetID int64
	if userIDStr != "" {
		targetID, _ = strconv.ParseInt(userIDStr, 10, 64)
	} else {
		uid, _ := c.Get(mw.CtxUserIDKey)
		targetID, _ = uid.(int64)
	}
	if targetID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "user_id required"))
		return
	}

	items, total, err := service.GetVideoList(ctx, targetID, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "items": items}))
}

// GetPopularVideos .
// @router /video/popular [GET]
func GetPopularVideos(ctx context.Context, c *app.RequestContext) {
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	items, total, err := service.GetPopularVideos(ctx, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "items": items}))
}

// SearchVideo .
// @router /video/search [POST]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var body struct {
		Keyword  string `json:"keyword"`
		PageNum  int    `json:"page_num"`
		PageSize int    `json:"page_size"`
	}
	if err := c.BindJSON(&body); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	if body.Keyword == "" {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "keyword required"))
		return
	}
	items, total, err := service.SearchVideo(ctx, body.Keyword, body.PageNum, body.PageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "items": items}))
}

// GetVideoDetail .
// @router /video/detail [GET]
func GetVideoDetail(ctx context.Context, c *app.RequestContext) {
	videoIDStr := c.Query("video_id")
	videoID, _ := strconv.ParseInt(videoIDStr, 10, 64)
	if videoID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "video_id required"))
		return
	}
	item, err := service.GetVideoDetail(ctx, videoID)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"video": item}))
}

// LikeAction .
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)

	var body struct {
		VideoID    *int64 `json:"video_id"`
		CommentID  *int64 `json:"comment_id"`
		ActionType int    `json:"action_type"`
	}
	if err := c.BindJSON(&body); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}

	if body.VideoID == nil && body.CommentID == nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "video_id or comment_id required"))
		return
	}

	var err error
	if body.VideoID != nil {
		err = service.LikeVideo(ctx, userID, *body.VideoID, body.ActionType)
	} else {
		err = service.LikeComment(ctx, userID, *body.CommentID, body.ActionType)
	}

	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(nil))
}

// GetLikeList .
// @router /like/list [GET]
func GetLikeList(ctx context.Context, c *app.RequestContext) {
	userIDStr := c.Query("user_id")
	userID, _ := strconv.ParseInt(userIDStr, 10, 64)
	if userID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "user_id required"))
		return
	}
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	items, total, err := service.GetLikeList(ctx, userID, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "items": items}))
}

// PublishComment .
// @router /comment/publish [POST]
func PublishComment(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)

	var body struct {
		VideoID   *int64 `json:"video_id"`
		CommentID *int64 `json:"comment_id"`
		Content   string `json:"content"`
	}
	if err := c.BindJSON(&body); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}

	if body.VideoID == nil && body.CommentID == nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "video_id or comment_id required"))
		return
	}

	var videoID int64
	var parentID int64
	if body.CommentID != nil {
		parentID = *body.CommentID
	} else {
		videoID = *body.VideoID
	}

	item, err := service.PublishComment(ctx, userID, videoID, parentID, body.Content)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"comment": item}))
}

// GetCommentList .
// @router /comment/list [GET]
func GetCommentList(ctx context.Context, c *app.RequestContext) {
	videoIDStr := c.Query("video_id")
	commentIDStr := c.Query("comment_id")
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	videoID, _ := strconv.ParseInt(videoIDStr, 10, 64)
	parentID, _ := strconv.ParseInt(commentIDStr, 10, 64)

	if videoID == 0 && parentID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "video_id or comment_id required"))
		return
	}

	items, total, err := service.GetCommentList(ctx, videoID, parentID, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "items": items}))
}

// DeleteComment .
// @router /comment/delete [DELETE]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)

	commentIDStr := c.Query("comment_id")
	commentID, _ := strconv.ParseInt(commentIDStr, 10, 64)
	if commentID == 0 {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, "comment_id required"))
		return
	}
	if err := service.DeleteComment(ctx, userID, commentID); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(nil))
}

// RelationAction .
// @router /relation/action [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)

	var body struct {
		ToUserID   int64 `json:"to_user_id"`
		ActionType int   `json:"action_type"`
	}
	if err := c.BindJSON(&body); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	if err := service.RelationAction(ctx, userID, body.ToUserID, body.ActionType); err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeBadRequest, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(nil))
}

// GetFollowingList .
// @router /following/list [GET]
func GetFollowingList(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	items, total, err := service.GetFollowingList(ctx, userID, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "users": items}))
}

// GetFollowerList .
// @router /follower/list [GET]
func GetFollowerList(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	items, total, err := service.GetFollowerList(ctx, userID, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "users": items}))
}

// GetFriendsList .
// @router /friends/list [GET]
func GetFriendsList(ctx context.Context, c *app.RequestContext) {
	uid, _ := c.Get(mw.CtxUserIDKey)
	userID, _ := uid.(int64)
	pageNum, _ := strconv.Atoi(c.DefaultQuery("page_num", "1"))
	pageSize, _ := strconv.Atoi(c.DefaultQuery("page_size", "10"))

	items, total, err := service.GetFriendsList(ctx, userID, pageNum, pageSize)
	if err != nil {
		c.JSON(consts.StatusOK, response.Fail(response.CodeInternalError, err.Error()))
		return
	}
	c.JSON(consts.StatusOK, response.Success(map[string]interface{}{"total": total, "users": items}))
}
