// Code generated by hertz generator.

package api

import (
	"github.com/BiliGO/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc { return nil }

// ==================== 无需鉴权 ====================

func _registerMw() []app.HandlerFunc { return nil }
func _loginMw() []app.HandlerFunc    { return nil }

// 视频浏览类接口无需登录
func _getvideolistMw() []app.HandlerFunc     { return nil }
func _getpopularvideosMw() []app.HandlerFunc { return nil }
func _searchvideoMw() []app.HandlerFunc      { return nil }
func _getcommentlistMw() []app.HandlerFunc   { return nil }

// ==================== 需要 JWT 鉴权 ====================

func jwt() []app.HandlerFunc { return []app.HandlerFunc{mw.JWTAuth()} }

func _userMw() []app.HandlerFunc         { return nil }
func _getuserinfoMw() []app.HandlerFunc  { return jwt() }
func _avatarMw() []app.HandlerFunc       { return nil }
func _uploadavatarMw() []app.HandlerFunc { return jwt() }

func _videoMw() []app.HandlerFunc { return nil }
func _publishvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.MaxBodySize(500 * 1024 * 1024), mw.JWTAuth()}
}

func _likeMw() []app.HandlerFunc        { return nil }
func _likeactionMw() []app.HandlerFunc  { return jwt() }
func _getlikelistMw() []app.HandlerFunc { return jwt() }

func _commentMw() []app.HandlerFunc        { return nil }
func _publishcommentMw() []app.HandlerFunc { return jwt() }
func _deletecommentMw() []app.HandlerFunc  { return jwt() }

func _relationMw() []app.HandlerFunc       { return nil }
func _relationactionMw() []app.HandlerFunc { return jwt() }

func _followerMw() []app.HandlerFunc        { return nil }
func _getfollowerlistMw() []app.HandlerFunc { return jwt() }

func _followingMw() []app.HandlerFunc        { return nil }
func _getfollowinglistMw() []app.HandlerFunc { return jwt() }

func _friendsMw() []app.HandlerFunc        { return nil }
func _getfriendslistMw() []app.HandlerFunc { return jwt() }
