// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"gobili/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/avatar/upload",
				Handler: UploadAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/image/search",
				Handler: ImageSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/bind",
				Handler: BindMfaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/qrcode",
				Handler: GetMfaQrcodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth/mfa"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: FeedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: VideoListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/popular",
				Handler: PopularHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: PublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: SearchVideoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/video"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: LikeActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: LikeListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/like"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/delete",
				Handler: DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: CommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: CommentPublishHandler(serverCtx),
			},
		},
		rest.WithPrefix("/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: RelationActionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/relation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: FollowingListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/following"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: FollowerListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/follower"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: FriendListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/friends"),
	)
}
