// Code generated by hertz generator.

package api

import (
	"context"

	api "gobili/api/model/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetFeed .
// @router /video/feed [GET]
func GetFeed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.FeedResponse)

	c.JSON(consts.StatusOK, resp)
}

// PublishVideo .
// @router /video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PublishVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoList .
// @router /video/list [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetVideoListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetVideoListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetPopularVideos .
// @router /video/popular [GET]
func GetPopularVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.GetPopularVideosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.GetPopularVideosResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideos .
// @router /video/search [POST]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchVideosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SearchVideosResponse)

	c.JSON(consts.StatusOK, resp)
}

// VisitVideo .
// @router /video/visit [POST]
func VisitVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VisitVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VisitVideoResponse)

	c.JSON(consts.StatusOK, resp)
}
