// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Base struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type BaseResp struct {
	Base Base `json:"base"`
}

type BindMfaReq struct {
	Code   string `form:"code"`
	Secret string `form:"secret"`
}

type Comment struct {
	Id         string `json:"id"`
	UserId     string `json:"user_id"`
	VideoId    string `json:"video_id"`
	ParentId   string `json:"parent_id"`
	LikeCount  int64  `json:"like_count"`
	ChildCount int64  `json:"child_count"`
	Content    string `json:"content"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	DeletedAt  string `json:"deleted_at"`
}

type CommentListData struct {
	Items []Comment `json:"items"`
}

type CommentListReq struct {
	VideoId   string `form:"video_id,optional"`
	CommentId string `form:"comment_id,optional"`
	PageSize  int64  `form:"page_size,optional"`
	PageNum   int64  `form:"page_num,optional"`
}

type CommentListResp struct {
	Base Base            `json:"base"`
	Data CommentListData `json:"data"`
}

type CommentPublishReq struct {
	VideoId   string `form:"video_id,optional"`
	CommentId string `form:"comment_id,optional"`
	Content   string `form:"content"`
}

type DeleteCommentReq struct {
	VideoId   string `form:"video_id,optional"`
	CommentId string `form:"comment_id,optional"`
}

type FeedReq struct {
	LatestTime string `form:"latest_time,optional"`
}

type FriendListReq struct {
	PageNum  int64 `form:"page_num,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type ImageSearchResp struct {
	Base Base   `json:"base"`
	Data string `json:"data"`
}

type LikeActionReq struct {
	VideoId    string `form:"video_id,optional"`
	CommentId  string `form:"comment_id,optional"`
	ActionType string `form:"action_type"`
}

type LikeListReq struct {
	UserId   string `form:"user_id,optional"`
	PageSize int64  `form:"page_size,optional"`
	PageNum  int64  `form:"page_num,optional"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Code     string `form:"code,optional"`
}

type MfaQRCodeResp struct {
	Base Base              `json:"base"`
	Data MfaQRCodeRespData `json:"data"`
}

type MfaQRCodeRespData struct {
	Secret string `json:"secret"`
	Qrcode string `json:"qrcode"`
}

type PagedVideoListData struct {
	Items []Video `json:"items"`
	Total int64   `json:"total"`
}

type PagedVideoListResp struct {
	Base Base               `json:"base"`
	Data PagedVideoListData `json:"data"`
}

type PopularReq struct {
	PageSize int64 `form:"page_size,optional"`
	PageNum  int64 `form:"page_num,optional"`
}

type VisitVideoReq struct {
	VideoId string `form:"video_id"`
}

type PublishListReq struct {
	UserId   string `form:"user_id"`
	PageNum  int64  `form:"page_num"`
	PageSize int64  `form:"page_size"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RelationActionReq struct {
	ToUserId   string `form:"to_user_id"`
	ActionType int64  `form:"action_type"`
}

type RelationListReq struct {
	UserId   string `form:"user_id"`
	PageNum  int64  `form:"page_num,optional"`
	PageSize int64  `form:"page_size,optional"`
}

type SearchVideoReq struct {
	Keywords string `form:"keywords,optional"`
	PageSize int64  `form:"page_size,optional"`
	PageNum  int64  `form:"page_num,optional"`
	FromDate int64  `form:"from_date,optional"`
	ToDate   int64  `form:"to_date,optional"`
	Username string `form:"username,optional"`
}

type SocialListData struct {
	Items []SocialUser `json:"items"`
	Total int64        `json:"total"`
}

type SocialListResp struct {
	Base Base           `json:"base"`
	Data SocialListData `json:"data"`
}

type SocialUser struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	AvatarUrl string `json:"avatar_url"`
}

type User struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	AvatarUrl string `json:"avatar_url"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	DeletedAt string `json:"deleted_at"`
}

type UserInfoReq struct {
	UserId string `form:"user_id,optional"`
}

type UserResp struct {
	Base Base `json:"base"`
	Data User `json:"data"`
}

type Video struct {
	Id           string `json:"id"`
	UserId       string `json:"user_id"`
	VideoUrl     string `json:"video_url"`
	CoverUrl     string `json:"cover_url"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	VisitCount   int64  `json:"visit_count"`
	LikeCount    int64  `json:"like_count"`
	CommentCount int64  `json:"comment_count"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
	DeletedAt    string `json:"deleted_at"`
}

type VideoListData struct {
	Items []Video `json:"items"`
}

type VideoListResp struct {
	Base Base          `json:"base"`
	Data VideoListData `json:"data"`
}
