// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package model

import (
	"fmt"
)

// BaseResp 是统一响应信封的模型定义。
// 注意：api.thrift 的响应体只描述 data 部分，信封由 api/pack 统一拼装，
// 这里保留 BaseResp 仅用于声明信封形态，供后续 RPC 化时复用。
type BaseResp struct {
	Code    string `thrift:"code,1,required" form:"code,required" json:"code,required" query:"code,required"`
	Message string `thrift:"message,2,required" form:"message,required" json:"message,required" query:"message,required"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v string) {
	return p.Code
}

func (p *BaseResp) GetMessage() (v string) {
	return p.Message
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

type User struct {
	ID        string `thrift:"id,1,required" form:"id,required" json:"id,required" query:"id,required"`
	Username  string `thrift:"username,2,required" form:"username,required" json:"username,required" query:"username,required"`
	AvatarURL string `thrift:"avatar_url,3,required" form:"avatar_url,required" json:"avatar_url,required" query:"avatar_url,required"`
	CreatedAt string `thrift:"created_at,4,required" form:"created_at,required" json:"created_at,required" query:"created_at,required"`
	UpdatedAt string `thrift:"updated_at,5,required" form:"updated_at,required" json:"updated_at,required" query:"updated_at,required"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetID() (v string) {
	return p.ID
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetAvatarURL() (v string) {
	return p.AvatarURL
}

func (p *User) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *User) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

type Video struct {
	ID           string `thrift:"id,1,required" form:"id,required" json:"id,required" query:"id,required"`
	UserID       string `thrift:"user_id,2,required" form:"user_id,required" json:"user_id,required" query:"user_id,required"`
	VideoURL     string `thrift:"video_url,3,required" form:"video_url,required" json:"video_url,required" query:"video_url,required"`
	CoverURL     string `thrift:"cover_url,4,required" form:"cover_url,required" json:"cover_url,required" query:"cover_url,required"`
	Title        string `thrift:"title,5,required" form:"title,required" json:"title,required" query:"title,required"`
	Description  string `thrift:"description,6,required" form:"description,required" json:"description,required" query:"description,required"`
	VisitCount   int64  `thrift:"visit_count,7,required" form:"visit_count,required" json:"visit_count,required" query:"visit_count,required"`
	CommentCount int64  `thrift:"comment_count,8,required" form:"comment_count,required" json:"comment_count,required" query:"comment_count,required"`
	CreatedAt    string `thrift:"created_at,9,required" form:"created_at,required" json:"created_at,required" query:"created_at,required"`
	UpdatedAt    string `thrift:"updated_at,10,required" form:"updated_at,required" json:"updated_at,required" query:"updated_at,required"`
}

func NewVideo() *Video {
	return &Video{}
}

func (p *Video) InitDefault() {
}

func (p *Video) GetID() (v string) {
	return p.ID
}

func (p *Video) GetUserID() (v string) {
	return p.UserID
}

func (p *Video) GetVideoURL() (v string) {
	return p.VideoURL
}

func (p *Video) GetCoverURL() (v string) {
	return p.CoverURL
}

func (p *Video) GetTitle() (v string) {
	return p.Title
}

func (p *Video) GetDescription() (v string) {
	return p.Description
}

func (p *Video) GetVisitCount() (v int64) {
	return p.VisitCount
}

func (p *Video) GetCommentCount() (v int64) {
	return p.CommentCount
}

func (p *Video) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Video) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *Video) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Video(%+v)", *p)
}

type Comment struct {
	ID         string `thrift:"id,1,required" form:"id,required" json:"id,required" query:"id,required"`
	UserID     string `thrift:"user_id,2,required" form:"user_id,required" json:"user_id,required" query:"user_id,required"`
	VideoID    string `thrift:"video_id,3,required" form:"video_id,required" json:"video_id,required" query:"video_id,required"`
	ParentID   string `thrift:"parent_id,4,required" form:"parent_id,required" json:"parent_id,required" query:"parent_id,required"`
	ChildCount int64  `thrift:"child_count,5,required" form:"child_count,required" json:"child_count,required" query:"child_count,required"`
	Content    string `thrift:"content,6,required" form:"content,required" json:"content,required" query:"content,required"`
	CreatedAt  string `thrift:"created_at,7,required" form:"created_at,required" json:"created_at,required" query:"created_at,required"`
	UpdatedAt  string `thrift:"updated_at,8,required" form:"updated_at,required" json:"updated_at,required" query:"updated_at,required"`
}

func NewComment() *Comment {
	return &Comment{}
}

func (p *Comment) InitDefault() {
}

func (p *Comment) GetID() (v string) {
	return p.ID
}

func (p *Comment) GetUserID() (v string) {
	return p.UserID
}

func (p *Comment) GetVideoID() (v string) {
	return p.VideoID
}

func (p *Comment) GetParentID() (v string) {
	return p.ParentID
}

func (p *Comment) GetChildCount() (v int64) {
	return p.ChildCount
}

func (p *Comment) GetContent() (v string) {
	return p.Content
}

func (p *Comment) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Comment) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *Comment) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Comment(%+v)", *p)
}
