// Code generated by hertz generator.

package auth

import (
	"github.com/BiliGO/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc { return nil }

func _authMw() []app.HandlerFunc         { return nil }
func _mfaMw() []app.HandlerFunc          { return nil }
func _getmfaqrcodeMw() []app.HandlerFunc { return []app.HandlerFunc{mw.JWTAuth()} }
