// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindmfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmfaqrcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfeedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpopularvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _visitvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
