// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api "github.com/BiliGO/biz/router/api"
	api_auth "github.com/BiliGO/biz/router/api/auth"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_auth.Register(r)

	api.Register(r)
}
