// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"gobili/api/model/model"
)

// # ----------------------------------------------------------------------------
// # 用户 / MFA
// # ----------------------------------------------------------------------------
type RegisterRequest struct {
	Username string `thrift:"username,1,required" form:"username,required" json:"username,required" query:"username,required"`
	Password string `thrift:"password,2,required" form:"password,required" json:"password,required" query:"password,required"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

type RegisterResponse struct {
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

type LoginRequest struct {
	Username string `thrift:"username,1,required" form:"username,required" json:"username,required" query:"username,required"`
	Password string `thrift:"password,2,required" form:"password,required" json:"password,required" query:"password,required"`
	// code 为 MFA 验证码，账号未开启 MFA 时可不传
	Code *string `thrift:"code,3,optional" form:"code" json:"code,omitempty" query:"code"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetUsername() (v string) {
	return p.Username
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}

var LoginRequest_Code_DEFAULT string

func (p *LoginRequest) GetCode() (v string) {
	if !p.IsSetCode() {
		return LoginRequest_Code_DEFAULT
	}
	return *p.Code
}

func (p *LoginRequest) IsSetCode() bool {
	return p.Code != nil
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

type LoginResponse struct {
	Data *model.User `thrift:"data,1,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_Data_DEFAULT *model.User

func (p *LoginResponse) GetData() (v *model.User) {
	if !p.IsSetData() {
		return LoginResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *LoginResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

type GetUserInfoRequest struct {
	// user_id 为空时查询当前登录用户
	UserID *string `thrift:"user_id,1,optional" form:"user_id" json:"user_id,omitempty" query:"user_id"`
}

func NewGetUserInfoRequest() *GetUserInfoRequest {
	return &GetUserInfoRequest{}
}

func (p *GetUserInfoRequest) InitDefault() {
}

var GetUserInfoRequest_UserID_DEFAULT string

func (p *GetUserInfoRequest) GetUserID() (v string) {
	if !p.IsSetUserID() {
		return GetUserInfoRequest_UserID_DEFAULT
	}
	return *p.UserID
}

func (p *GetUserInfoRequest) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *GetUserInfoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoRequest(%+v)", *p)
}

type GetUserInfoResponse struct {
	Data *model.User `thrift:"data,1,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewGetUserInfoResponse() *GetUserInfoResponse {
	return &GetUserInfoResponse{}
}

func (p *GetUserInfoResponse) InitDefault() {
}

var GetUserInfoResponse_Data_DEFAULT *model.User

func (p *GetUserInfoResponse) GetData() (v *model.User) {
	if !p.IsSetData() {
		return GetUserInfoResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *GetUserInfoResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *GetUserInfoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResponse(%+v)", *p)
}

// UploadAvatar 与 PublishVideo 为 multipart/form-data 接口，
// 文件通过 c.FormFile("file") 读取，因此请求体本身没有字段。
// 注意：hz 生成 model 后需要手工调整，详见 Makefile 注释。
type UploadAvatarRequest struct {
}

func NewUploadAvatarRequest() *UploadAvatarRequest {
	return &UploadAvatarRequest{}
}

func (p *UploadAvatarRequest) InitDefault() {
}

func (p *UploadAvatarRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarRequest(%+v)", *p)
}

type UploadAvatarResponse struct {
	Data *model.User `thrift:"data,1,optional" form:"data" json:"data,omitempty" query:"data"`
}

func NewUploadAvatarResponse() *UploadAvatarResponse {
	return &UploadAvatarResponse{}
}

func (p *UploadAvatarResponse) InitDefault() {
}

var UploadAvatarResponse_Data_DEFAULT *model.User

func (p *UploadAvatarResponse) GetData() (v *model.User) {
	if !p.IsSetData() {
		return UploadAvatarResponse_Data_DEFAULT
	}
	return p.Data
}

func (p *UploadAvatarResponse) IsSetData() bool {
	return p.Data != nil
}

func (p *UploadAvatarResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadAvatarResponse(%+v)", *p)
}

type GetMfaQRCodeRequest struct {
}

func NewGetMfaQRCodeRequest() *GetMfaQRCodeRequest {
	return &GetMfaQRCodeRequest{}
}

func (p *GetMfaQRCodeRequest) InitDefault() {
}

func (p *GetMfaQRCodeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMfaQRCodeRequest(%+v)", *p)
}

type GetMfaQRCodeResponse struct {
	Secret string `thrift:"secret,1,required" form:"secret,required" json:"secret,required" query:"secret,required"`
	Qrcode string `thrift:"qrcode,2,required" form:"qrcode,required" json:"qrcode,required" query:"qrcode,required"`
}

func NewGetMfaQRCodeResponse() *GetMfaQRCodeResponse {
	return &GetMfaQRCodeResponse{}
}

func (p *GetMfaQRCodeResponse) InitDefault() {
}

func (p *GetMfaQRCodeResponse) GetSecret() (v string) {
	return p.Secret
}

func (p *GetMfaQRCodeResponse) GetQrcode() (v string) {
	return p.Qrcode
}

func (p *GetMfaQRCodeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetMfaQRCodeResponse(%+v)", *p)
}

type BindMfaRequest struct {
	Code   string `thrift:"code,1,required" form:"code,required" json:"code,required" query:"code,required"`
	Secret string `thrift:"secret,2,required" form:"secret,required" json:"secret,required" query:"secret,required"`
}

func NewBindMfaRequest() *BindMfaRequest {
	return &BindMfaRequest{}
}

func (p *BindMfaRequest) InitDefault() {
}

func (p *BindMfaRequest) GetCode() (v string) {
	return p.Code
}

func (p *BindMfaRequest) GetSecret() (v string) {
	return p.Secret
}

func (p *BindMfaRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindMfaRequest(%+v)", *p)
}

type BindMfaResponse struct {
}

func NewBindMfaResponse() *BindMfaResponse {
	return &BindMfaResponse{}
}

func (p *BindMfaResponse) InitDefault() {
}

func (p *BindMfaResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BindMfaResponse(%+v)", *p)
}

// # ----------------------------------------------------------------------------
// # 视频
// # ----------------------------------------------------------------------------
type FeedRequest struct {
	// latest_time 为毫秒时间戳，返回该时间之后的最新视频
	LatestTime *string `thrift:"latest_time,1,optional" form:"latest_time" json:"latest_time,omitempty" query:"latest_time"`
}

func NewFeedRequest() *FeedRequest {
	return &FeedRequest{}
}

func (p *FeedRequest) InitDefault() {
}

var FeedRequest_LatestTime_DEFAULT string

func (p *FeedRequest) GetLatestTime() (v string) {
	if !p.IsSetLatestTime() {
		return FeedRequest_LatestTime_DEFAULT
	}
	return *p.LatestTime
}

func (p *FeedRequest) IsSetLatestTime() bool {
	return p.LatestTime != nil
}

func (p *FeedRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedRequest(%+v)", *p)
}

type FeedResponse struct {
	Items []*model.Video `thrift:"items,1,optional,list<model.Video>" form:"items" json:"items,omitempty" query:"items"`
}

func NewFeedResponse() *FeedResponse {
	return &FeedResponse{}
}

func (p *FeedResponse) InitDefault() {
}

var FeedResponse_Items_DEFAULT []*model.Video

func (p *FeedResponse) GetItems() (v []*model.Video) {
	if !p.IsSetItems() {
		return FeedResponse_Items_DEFAULT
	}
	return p.Items
}

func (p *FeedResponse) IsSetItems() bool {
	return p.Items != nil
}

func (p *FeedResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FeedResponse(%+v)", *p)
}

type PublishVideoRequest struct {
}

func NewPublishVideoRequest() *PublishVideoRequest {
	return &PublishVideoRequest{}
}

func (p *PublishVideoRequest) InitDefault() {
}

func (p *PublishVideoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoRequest(%+v)", *p)
}

type PublishVideoResponse struct {
}

func NewPublishVideoResponse() *PublishVideoResponse {
	return &PublishVideoResponse{}
}

func (p *PublishVideoResponse) InitDefault() {
}

func (p *PublishVideoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishVideoResponse(%+v)", *p)
}

type GetVideoListRequest struct {
	UserID   string `thrift:"user_id,1,required" form:"user_id,required" json:"user_id,required" query:"user_id,required"`
	PageNum  *int64 `thrift:"page_num,2,optional" form:"page_num" json:"page_num,omitempty" query:"page_num"`
	PageSize *int64 `thrift:"page_size,3,optional" form:"page_size" json:"page_size,omitempty" query:"page_size"`
}

func NewGetVideoListRequest() *GetVideoListRequest {
	return &GetVideoListRequest{}
}

func (p *GetVideoListRequest) InitDefault() {
}

func (p *GetVideoListRequest) GetUserID() (v string) {
	return p.UserID
}

var GetVideoListRequest_PageNum_DEFAULT int64

func (p *GetVideoListRequest) GetPageNum() (v int64) {
	if !p.IsSetPageNum() {
		return GetVideoListRequest_PageNum_DEFAULT
	}
	return *p.PageNum
}

var GetVideoListRequest_PageSize_DEFAULT int64

func (p *GetVideoListRequest) GetPageSize() (v int64) {
	if !p.IsSetPageSize() {
		return GetVideoListRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

func (p *GetVideoListRequest) IsSetPageNum() bool {
	return p.PageNum != nil
}

func (p *GetVideoListRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *GetVideoListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoListRequest(%+v)", *p)
}

type GetVideoListResponse struct {
	Items []*model.Video `thrift:"items,1,optional,list<model.Video>" form:"items" json:"items,omitempty" query:"items"`
	Total *int64         `thrift:"total,2,optional" form:"total" json:"total,omitempty" query:"total"`
}

func NewGetVideoListResponse() *GetVideoListResponse {
	return &GetVideoListResponse{}
}

func (p *GetVideoListResponse) InitDefault() {
}

var GetVideoListResponse_Items_DEFAULT []*model.Video

func (p *GetVideoListResponse) GetItems() (v []*model.Video) {
	if !p.IsSetItems() {
		return GetVideoListResponse_Items_DEFAULT
	}
	return p.Items
}

var GetVideoListResponse_Total_DEFAULT int64

func (p *GetVideoListResponse) GetTotal() (v int64) {
	if !p.IsSetTotal() {
		return GetVideoListResponse_Total_DEFAULT
	}
	return *p.Total
}

func (p *GetVideoListResponse) IsSetItems() bool {
	return p.Items != nil
}

func (p *GetVideoListResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *GetVideoListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoListResponse(%+v)", *p)
}

type GetPopularVideosRequest struct {
	PageNum  *int64 `thrift:"page_num,1,optional" form:"page_num" json:"page_num,omitempty" query:"page_num"`
	PageSize *int64 `thrift:"page_size,2,optional" form:"page_size" json:"page_size,omitempty" query:"page_size"`
}

func NewGetPopularVideosRequest() *GetPopularVideosRequest {
	return &GetPopularVideosRequest{}
}

func (p *GetPopularVideosRequest) InitDefault() {
}

var GetPopularVideosRequest_PageNum_DEFAULT int64

func (p *GetPopularVideosRequest) GetPageNum() (v int64) {
	if !p.IsSetPageNum() {
		return GetPopularVideosRequest_PageNum_DEFAULT
	}
	return *p.PageNum
}

var GetPopularVideosRequest_PageSize_DEFAULT int64

func (p *GetPopularVideosRequest) GetPageSize() (v int64) {
	if !p.IsSetPageSize() {
		return GetPopularVideosRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

func (p *GetPopularVideosRequest) IsSetPageNum() bool {
	return p.PageNum != nil
}

func (p *GetPopularVideosRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *GetPopularVideosRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPopularVideosRequest(%+v)", *p)
}

type GetPopularVideosResponse struct {
	Items []*model.Video `thrift:"items,1,optional,list<model.Video>" form:"items" json:"items,omitempty" query:"items"`
	Total *int64         `thrift:"total,2,optional" form:"total" json:"total,omitempty" query:"total"`
}

func NewGetPopularVideosResponse() *GetPopularVideosResponse {
	return &GetPopularVideosResponse{}
}

func (p *GetPopularVideosResponse) InitDefault() {
}

var GetPopularVideosResponse_Items_DEFAULT []*model.Video

func (p *GetPopularVideosResponse) GetItems() (v []*model.Video) {
	if !p.IsSetItems() {
		return GetPopularVideosResponse_Items_DEFAULT
	}
	return p.Items
}

var GetPopularVideosResponse_Total_DEFAULT int64

func (p *GetPopularVideosResponse) GetTotal() (v int64) {
	if !p.IsSetTotal() {
		return GetPopularVideosResponse_Total_DEFAULT
	}
	return *p.Total
}

func (p *GetPopularVideosResponse) IsSetItems() bool {
	return p.Items != nil
}

func (p *GetPopularVideosResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *GetPopularVideosResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPopularVideosResponse(%+v)", *p)
}

type SearchVideosRequest struct {
	Keywords *string `thrift:"keywords,1,optional" form:"keywords" json:"keywords,omitempty" query:"keywords"`
	// from_date / to_date 为毫秒时间戳，用于限定投稿时间区间
	FromDate *int64  `thrift:"from_date,2,optional" form:"from_date" json:"from_date,omitempty" query:"from_date"`
	ToDate   *int64  `thrift:"to_date,3,optional" form:"to_date" json:"to_date,omitempty" query:"to_date"`
	Username *string `thrift:"username,4,optional" form:"username" json:"username,omitempty" query:"username"`
	PageNum  *int64  `thrift:"page_num,5,optional" form:"page_num" json:"page_num,omitempty" query:"page_num"`
	PageSize *int64  `thrift:"page_size,6,optional" form:"page_size" json:"page_size,omitempty" query:"page_size"`
}

func NewSearchVideosRequest() *SearchVideosRequest {
	return &SearchVideosRequest{}
}

func (p *SearchVideosRequest) InitDefault() {
}

var SearchVideosRequest_Keywords_DEFAULT string

func (p *SearchVideosRequest) GetKeywords() (v string) {
	if !p.IsSetKeywords() {
		return SearchVideosRequest_Keywords_DEFAULT
	}
	return *p.Keywords
}

var SearchVideosRequest_FromDate_DEFAULT int64

func (p *SearchVideosRequest) GetFromDate() (v int64) {
	if !p.IsSetFromDate() {
		return SearchVideosRequest_FromDate_DEFAULT
	}
	return *p.FromDate
}

var SearchVideosRequest_ToDate_DEFAULT int64

func (p *SearchVideosRequest) GetToDate() (v int64) {
	if !p.IsSetToDate() {
		return SearchVideosRequest_ToDate_DEFAULT
	}
	return *p.ToDate
}

var SearchVideosRequest_Username_DEFAULT string

func (p *SearchVideosRequest) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return SearchVideosRequest_Username_DEFAULT
	}
	return *p.Username
}

var SearchVideosRequest_PageNum_DEFAULT int64

func (p *SearchVideosRequest) GetPageNum() (v int64) {
	if !p.IsSetPageNum() {
		return SearchVideosRequest_PageNum_DEFAULT
	}
	return *p.PageNum
}

var SearchVideosRequest_PageSize_DEFAULT int64

func (p *SearchVideosRequest) GetPageSize() (v int64) {
	if !p.IsSetPageSize() {
		return SearchVideosRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

func (p *SearchVideosRequest) IsSetKeywords() bool {
	return p.Keywords != nil
}

func (p *SearchVideosRequest) IsSetFromDate() bool {
	return p.FromDate != nil
}

func (p *SearchVideosRequest) IsSetToDate() bool {
	return p.ToDate != nil
}

func (p *SearchVideosRequest) IsSetUsername() bool {
	return p.Username != nil
}

func (p *SearchVideosRequest) IsSetPageNum() bool {
	return p.PageNum != nil
}

func (p *SearchVideosRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *SearchVideosRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchVideosRequest(%+v)", *p)
}

type SearchVideosResponse struct {
	Items []*model.Video `thrift:"items,1,optional,list<model.Video>" form:"items" json:"items,omitempty" query:"items"`
	Total *int64         `thrift:"total,2,optional" form:"total" json:"total,omitempty" query:"total"`
}

func NewSearchVideosResponse() *SearchVideosResponse {
	return &SearchVideosResponse{}
}

func (p *SearchVideosResponse) InitDefault() {
}

var SearchVideosResponse_Items_DEFAULT []*model.Video

func (p *SearchVideosResponse) GetItems() (v []*model.Video) {
	if !p.IsSetItems() {
		return SearchVideosResponse_Items_DEFAULT
	}
	return p.Items
}

var SearchVideosResponse_Total_DEFAULT int64

func (p *SearchVideosResponse) GetTotal() (v int64) {
	if !p.IsSetTotal() {
		return SearchVideosResponse_Total_DEFAULT
	}
	return *p.Total
}

func (p *SearchVideosResponse) IsSetItems() bool {
	return p.Items != nil
}

func (p *SearchVideosResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *SearchVideosResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SearchVideosResponse(%+v)", *p)
}

type VisitVideoRequest struct {
	VideoID string `thrift:"video_id,1,required" form:"video_id,required" json:"video_id,required" query:"video_id,required"`
}

func NewVisitVideoRequest() *VisitVideoRequest {
	return &VisitVideoRequest{}
}

func (p *VisitVideoRequest) InitDefault() {
}

func (p *VisitVideoRequest) GetVideoID() (v string) {
	return p.VideoID
}

func (p *VisitVideoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VisitVideoRequest(%+v)", *p)
}

type VisitVideoResponse struct {
}

func NewVisitVideoResponse() *VisitVideoResponse {
	return &VisitVideoResponse{}
}

func (p *VisitVideoResponse) InitDefault() {
}

func (p *VisitVideoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VisitVideoResponse(%+v)", *p)
}

// # ----------------------------------------------------------------------------
// # 评论
// # ----------------------------------------------------------------------------
type PublishCommentRequest struct {
	VideoID string `thrift:"video_id,1,required" form:"video_id,required" json:"video_id,required" query:"video_id,required"`
	// comment_id 非空时表示回复该评论
	CommentID *string `thrift:"comment_id,2,optional" form:"comment_id" json:"comment_id,omitempty" query:"comment_id"`
	Content   string  `thrift:"content,3,required" form:"content,required" json:"content,required" query:"content,required"`
}

func NewPublishCommentRequest() *PublishCommentRequest {
	return &PublishCommentRequest{}
}

func (p *PublishCommentRequest) InitDefault() {
}

func (p *PublishCommentRequest) GetVideoID() (v string) {
	return p.VideoID
}

var PublishCommentRequest_CommentID_DEFAULT string

func (p *PublishCommentRequest) GetCommentID() (v string) {
	if !p.IsSetCommentID() {
		return PublishCommentRequest_CommentID_DEFAULT
	}
	return *p.CommentID
}

func (p *PublishCommentRequest) GetContent() (v string) {
	return p.Content
}

func (p *PublishCommentRequest) IsSetCommentID() bool {
	return p.CommentID != nil
}

func (p *PublishCommentRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishCommentRequest(%+v)", *p)
}

type PublishCommentResponse struct {
}

func NewPublishCommentResponse() *PublishCommentResponse {
	return &PublishCommentResponse{}
}

func (p *PublishCommentResponse) InitDefault() {
}

func (p *PublishCommentResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishCommentResponse(%+v)", *p)
}

type GetCommentListRequest struct {
	VideoID string `thrift:"video_id,1,required" form:"video_id,required" json:"video_id,required" query:"video_id,required"`
	// comment_id 非空时查询该评论下的子评论
	CommentID *string `thrift:"comment_id,2,optional" form:"comment_id" json:"comment_id,omitempty" query:"comment_id"`
	PageNum   *int64  `thrift:"page_num,3,optional" form:"page_num" json:"page_num,omitempty" query:"page_num"`
	PageSize  *int64  `thrift:"page_size,4,optional" form:"page_size" json:"page_size,omitempty" query:"page_size"`
}

func NewGetCommentListRequest() *GetCommentListRequest {
	return &GetCommentListRequest{}
}

func (p *GetCommentListRequest) InitDefault() {
}

func (p *GetCommentListRequest) GetVideoID() (v string) {
	return p.VideoID
}

var GetCommentListRequest_CommentID_DEFAULT string

func (p *GetCommentListRequest) GetCommentID() (v string) {
	if !p.IsSetCommentID() {
		return GetCommentListRequest_CommentID_DEFAULT
	}
	return *p.CommentID
}

var GetCommentListRequest_PageNum_DEFAULT int64

func (p *GetCommentListRequest) GetPageNum() (v int64) {
	if !p.IsSetPageNum() {
		return GetCommentListRequest_PageNum_DEFAULT
	}
	return *p.PageNum
}

var GetCommentListRequest_PageSize_DEFAULT int64

func (p *GetCommentListRequest) GetPageSize() (v int64) {
	if !p.IsSetPageSize() {
		return GetCommentListRequest_PageSize_DEFAULT
	}
	return *p.PageSize
}

func (p *GetCommentListRequest) IsSetCommentID() bool {
	return p.CommentID != nil
}

func (p *GetCommentListRequest) IsSetPageNum() bool {
	return p.PageNum != nil
}

func (p *GetCommentListRequest) IsSetPageSize() bool {
	return p.PageSize != nil
}

func (p *GetCommentListRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCommentListRequest(%+v)", *p)
}

type GetCommentListResponse struct {
	Items []*model.Comment `thrift:"items,1,optional,list<model.Comment>" form:"items" json:"items,omitempty" query:"items"`
	Total *int64           `thrift:"total,2,optional" form:"total" json:"total,omitempty" query:"total"`
}

func NewGetCommentListResponse() *GetCommentListResponse {
	return &GetCommentListResponse{}
}

func (p *GetCommentListResponse) InitDefault() {
}

var GetCommentListResponse_Items_DEFAULT []*model.Comment

func (p *GetCommentListResponse) GetItems() (v []*model.Comment) {
	if !p.IsSetItems() {
		return GetCommentListResponse_Items_DEFAULT
	}
	return p.Items
}

var GetCommentListResponse_Total_DEFAULT int64

func (p *GetCommentListResponse) GetTotal() (v int64) {
	if !p.IsSetTotal() {
		return GetCommentListResponse_Total_DEFAULT
	}
	return *p.Total
}

func (p *GetCommentListResponse) IsSetItems() bool {
	return p.Items != nil
}

func (p *GetCommentListResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *GetCommentListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCommentListResponse(%+v)", *p)
}

type DeleteCommentRequest struct {
	CommentID string `thrift:"comment_id,1,required" form:"comment_id,required" json:"comment_id,required" query:"comment_id,required"`
}

func NewDeleteCommentRequest() *DeleteCommentRequest {
	return &DeleteCommentRequest{}
}

func (p *DeleteCommentRequest) InitDefault() {
}

func (p *DeleteCommentRequest) GetCommentID() (v string) {
	return p.CommentID
}

func (p *DeleteCommentRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCommentRequest(%+v)", *p)
}

type DeleteCommentResponse struct {
}

func NewDeleteCommentResponse() *DeleteCommentResponse {
	return &DeleteCommentResponse{}
}

func (p *DeleteCommentResponse) InitDefault() {
}

func (p *DeleteCommentResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteCommentResponse(%+v)", *p)
}

type UserService interface {
	// 用户注册
	Register(ctx context.Context, request *RegisterRequest) (r *RegisterResponse, err error)
	// 用户登录，成功后 Access-Token / Refresh-Token 通过响应头下发
	Login(ctx context.Context, request *LoginRequest) (r *LoginResponse, err error)
	// 获取用户信息
	GetUserInfo(ctx context.Context, request *GetUserInfoRequest) (r *GetUserInfoResponse, err error)
	// 上传头像
	UploadAvatar(ctx context.Context, request *UploadAvatarRequest) (r *UploadAvatarResponse, err error)
	// 获取 MFA 绑定二维码
	GetMfaQRCode(ctx context.Context, request *GetMfaQRCodeRequest) (r *GetMfaQRCodeResponse, err error)
	// 绑定 MFA
	BindMfa(ctx context.Context, request *BindMfaRequest) (r *BindMfaResponse, err error)
}

type VideoService interface {
	// 获取最新视频流
	GetFeed(ctx context.Context, request *FeedRequest) (r *FeedResponse, err error)
	// 投稿视频
	PublishVideo(ctx context.Context, request *PublishVideoRequest) (r *PublishVideoResponse, err error)
	// 获取指定用户的投稿列表
	GetVideoList(ctx context.Context, request *GetVideoListRequest) (r *GetVideoListResponse, err error)
	// 热门排行榜
	GetPopularVideos(ctx context.Context, request *GetPopularVideosRequest) (r *GetPopularVideosResponse, err error)
	// 多条件搜索视频
	SearchVideos(ctx context.Context, request *SearchVideosRequest) (r *SearchVideosResponse, err error)
	// 记录视频访问
	VisitVideo(ctx context.Context, request *VisitVideoRequest) (r *VisitVideoResponse, err error)
}

type CommentService interface {
	// 发表评论或回复评论
	PublishComment(ctx context.Context, request *PublishCommentRequest) (r *PublishCommentResponse, err error)
	// 获取评论列表
	GetCommentList(ctx context.Context, request *GetCommentListRequest) (r *GetCommentListResponse, err error)
	// 删除自己的评论
	DeleteComment(ctx context.Context, request *DeleteCommentRequest) (r *DeleteCommentResponse, err error)
}
